FROM node:18-alpine

WORKDIR /app

# Installing dependencies
COPY --chown=node:node package*.json /app
RUN npm install

# Copying source files
COPY --chown=node:node . /app

# Running the app
CMD "npm" "run" "dev"