export { iconFragment } from "./common"
export { imageFragment } from "./common"
export { slidesFragment } from "./common"
export { linkFragment } from "./common"
export { calloutFragment } from "./common"
export { cardsFragment } from "./common"
export { videoLinkFragment } from "./common"

export { pageCommonFragment } from "./page"
export { mainMenuQueryFragment } from "./page"
export { generalPageQuery } from "./page"
