query GetContactData {
  page(id: "about/contact", idType: URI) {
    ...PageCommonBase
    page_about_contact {
      acf {
        ...CardsFragment
        ...SalesRepFragment
        map {
          fieldGroupName
          markers {
            label
            center {
              lat
              lng
            }
            icon {
              name
              type
            }
          }
        }
      }
    }
  }
}
