query GetHomeData {
  productCategories(where: { hideEmpty: true }) {
    nodes {
      id
      name
      slug
      image {
        id
        databaseId
        altText
        sourceUrl
        mimeType
        mediaDetails {
          height
          width
        }
        fileSize
      }
      ancestors {
        nodes {
          id
        }
      }
    }
  }
  products(where: { orderby: { field: TOTAL_SALES, order: DESC } }, first: 8) {
    nodes {
      id
      name
      slug
      image {
        id
        databaseId
        altText
        sourceUrl
        mimeType
        mediaDetails {
          height
          width
        }
        fileSize
      }
      productCategories {
        nodes {
          slug
        }
      }
    }
  }
  page(id: "home", idType: URI) {
    ...PageCommonBase
    page_home {
      acf {
        hero {
          cards {
            title
            content
            icon {
              name
              type
            }
            image {
              id
              databaseId
              altText
              sourceUrl
              mimeType
              mediaDetails {
                height
                width
              }
              fileSize
            }
            link {
              url
              label
            }
          }
        }
        cards {
          title
          content
          icon {
            name
            type
          }
          image {
            ...ImageBase
          }
          link {
            url
            label
          }
        }
        videoLinks {
          videoLink {
            title
            provider
            videoId
            videoUrl
            placeholder {
              ...ImageBase
            }
            videoFile {
              ...ImageBase
            }
          }
        }
        ...FeaturedSupplierFragment
      }
    }
  }
}
