query GetMainMenu {
  menu(id: "main", idType: SLUG) {
    id
    menuItems(first: 100, where: { parentDatabaseId: 0 }) {
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
        id
        url
        label
        menuFields {
          mega
        }
        childItems {
          nodes {
            id
            url
            label
            menuFields {
              column
            }
            childItems {
              nodes {
                id
                url
                label
                childItems {
                  nodes {
                    id
                    url
                    label
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
