query GetMenu {
  menu(id: "main", idType: SLUG) {
    id
    menuItems(first: 100) {
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
        id
        databaseId
        url
        label
        parentDatabaseId
        menuFields {
          mega
          column
        }
        childItems {
          nodes {
            id
          }
        }
      }
    }
  }
}
