query GetProductDataBySlug($slug: ID!) {
  product(id: $slug, idType: SLUG) {
    ...VariableProductFragment
    ...SimpleProductFragment
    seo {
      title
      description
      focusKeywords
      openGraph {
        articleMeta {
          section
        }
        description
        locale
        siteName
        title
        type
        url
        slackEnhancedData {
          data
          label
        }
        twitterMeta {
          card
          description
          title
        }
      }
    }
  }
}
