query GetWarehousesData {
  page(id: "about/warehouses", idType: URI) {
    ...PageCommonBase
    page_about_warehouses {
      acf {
        map {
          fieldGroupName
          markers {
            label
            center {
              lat
              lng
            }
            icon {
              name
              type
            }
          }
        }
      }
    }
  }
}
