fragment EmployeeBase on Employee {
  id
  databaseId
  slug
  title
  position {
    position
  }
  departments {
    nodes {
      name
    }
  }
  contact {
    contact {
      office
      fax
      email
      address
      orders
    }
  }
}
