fragment CardsFragment on Page_PageAboutContact_Acf {
  cards {
    title
    content
    icon {
      name
      type
    }
    image {
      ...ImageBase
    }
    link {
      url
      label
    }
  }
}
