fragment PageCommonBase on Page {
  id
  databaseId
  title
  slug
  seo {
    title
    description
    focusKeywords
    openGraph {
      articleMeta {
        section
      }
      description
      locale
      siteName
      title
      type
      url
      slackEnhancedData {
        data
        label
      }
      twitterMeta {
        card
        description
        title
      }
    }
  }
}
