import { CollectionConfig } from "payload/types"

export const LancoWebhooks: CollectionConfig = {
  slug: "lancoWebhooks",
  admin: {
    group: "System",
    useAsTitle: "id",
    defaultColumns: ["id", "type", "processingStatus", "product", "createdAt"],
  },
  fields: [
    { name: "rawData", type: "json" },
    {
      name: "type",
      type: "select",
      options: [
        { label: "Created", value: "created" },
        { label: "Restored", value: "restored" },
        { label: "Updated", value: "updated" },
        { label: "Deleted", value: "deleted" },
      ],
    },
    {
      name: "processingStatus",
      type: "select",
      defaultValue: "pending",
      options: [
        { label: "Pending", value: "pending" },
        { label: "Success", value: "success" },
        { label: "Error", value: "error" },
      ],
      admin: {
        position: "sidebar",
      },
    },
    {
      name: "errorMessage",
      type: "textarea",
      admin: {
        condition: (data) => data.processingStatus === "error",
      },
    },
    {
      name: "processingLog",
      type: "textarea",
      admin: {
        description: "Detailed step-by-step processing log",
      },
    },
    { name: "product", type: "relationship", relationTo: "products" },
  ],
}

const createdData = {}

const updatedData = {
  id: 40679,
  name: "Uline 5500 lb. Capacity Extra Long Fork Pallet Jack MH2399C",
  slug: "uline-5500-lb-capacity-extra-long-fork-pallet-jack-mh2399c",
  permalink:
    "https://lanco-corp.com/product/uline-5500-lb-capacity-extra-long-fork-pallet-jack-mh2399c/",
  date_created: "2025-05-13T09:44:55",
  date_created_gmt: "2025-05-13T13:44:55",
  date_modified: "2025-05-13T09:47:08",
  date_modified_gmt: "2025-05-13T13:47:08",
  type: "simple",
  status: "publish",
  featured: true,
  catalog_visibility: "visible",
  description:
    "<p>Uline 5500 lb. Capacity Extra Long Fork Pallet Jack MH2399C</p>\n",
  short_description:
    "<p>3-Position Hand Control:  Raise, Lower and Neutral.</p>\n<p>3&#8243; Lowered and 7.50&#8243; Raised Height.</p>\n",
  sku: "MH2399C",
  price: "875",
  regular_price: "875",
  sale_price: "",
  date_on_sale_from: null,
  date_on_sale_from_gmt: null,
  date_on_sale_to: null,
  date_on_sale_to_gmt: null,
  on_sale: false,
  purchasable: true,
  total_sales: 0,
  virtual: false,
  downloadable: false,
  downloads: [],
  download_limit: -1,
  download_expiry: -1,
  external_url: "",
  button_text: "",
  tax_status: "taxable",
  tax_class: "",
  manage_stock: true,
  stock_quantity: 1,
  backorders: "no",
  backorders_allowed: false,
  backordered: false,
  low_stock_amount: null,
  sold_individually: false,
  weight: "9999",
  dimensions: { length: "", width: "", height: "" },
  shipping_required: true,
  shipping_taxable: true,
  shipping_class: "",
  shipping_class_id: 0,
  reviews_allowed: false,
  average_rating: "0.00",
  rating_count: 0,
  upsell_ids: [],
  cross_sell_ids: [],
  parent_id: 0,
  purchase_note: "",
  categories: [
    { id: 85, name: "Material Handling", slug: "material-handling" },
  ],
  tags: [],
  images: [
    {
      id: 40680,
      date_created: "2025-05-13T05:46:29",
      date_created_gmt: "2025-05-13T13:46:29",
      date_modified: "2025-05-13T05:46:29",
      date_modified_gmt: "2025-05-13T13:46:29",
      src: "https://lanco-corp.com/wp-content/uploads/2025/05/MH2399C-scaled.jpg",
      name: "MH2399C",
      alt: "",
    },
    {
      id: 40681,
      date_created: "2025-05-13T05:46:33",
      date_created_gmt: "2025-05-13T13:46:33",
      date_modified: "2025-05-13T05:46:33",
      date_modified_gmt: "2025-05-13T13:46:33",
      src: "https://lanco-corp.com/wp-content/uploads/2025/05/MH2399Ca-scaled.jpg",
      name: "MH2399Ca",
      alt: "",
    },
    {
      id: 40683,
      date_created: "2025-05-13T05:46:41",
      date_created_gmt: "2025-05-13T13:46:41",
      date_modified: "2025-05-13T05:46:41",
      date_modified_gmt: "2025-05-13T13:46:41",
      src: "https://lanco-corp.com/wp-content/uploads/2025/05/MH2399Cc-scaled.jpg",
      name: "MH2399Cc",
      alt: "",
    },
    {
      id: 40682,
      date_created: "2025-05-13T05:46:37",
      date_created_gmt: "2025-05-13T13:46:37",
      date_modified: "2025-05-13T05:46:37",
      date_modified_gmt: "2025-05-13T13:46:37",
      src: "https://lanco-corp.com/wp-content/uploads/2025/05/MH2399Cb-scaled.jpg",
      name: "MH2399Cb",
      alt: "",
    },
  ],
  attributes: [
    {
      id: 113,
      name: "New / Used",
      slug: "pa_new-used",
      position: 0,
      visible: true,
      variation: false,
      options: ["Used"],
    },
    {
      id: 4,
      name: "inventory",
      slug: "pa_inventory",
      position: 1,
      visible: true,
      variation: false,
      options: ["MH2399C"],
    },
    {
      id: 5,
      name: "Manufacturer",
      slug: "pa_manufacturer",
      position: 2,
      visible: true,
      variation: false,
      options: ["Uline"],
    },
    {
      id: 7,
      name: "model",
      slug: "pa_model",
      position: 3,
      visible: true,
      variation: false,
      options: ["H4123"],
    },
    {
      id: 27,
      name: "Type",
      slug: "pa_type-2",
      position: 4,
      visible: true,
      variation: false,
      options: ["Pallet Jack"],
    },
    {
      id: 112,
      name: "Capacity",
      slug: "pa_capacity",
      position: 5,
      visible: true,
      variation: false,
      options: ["5500"],
    },
    {
      id: 41,
      name: "dimensions",
      slug: "pa_dimensions",
      position: 6,
      visible: true,
      variation: false,
      options: ['96"L x 27"W'],
    },
  ],
  default_attributes: [],
  variations: [],
  grouped_products: [],
  menu_order: 2,
  price_html:
    '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>875.00</bdi></span>',
  related_ids: [2459, 4170, 11475, 7261, 8962],
  meta_data: [
    { id: 649668, key: "rank_math_internal_links_processed", value: "1" },
    { id: 649691, key: "rank_math_internal_links_processed", value: "1" },
    { id: 649692, key: "acqdate", value: "05/01/2025" },
    { id: 649693, key: "acqfrom", value: "Lacks" },
    { id: 649704, key: "rank_math_seo_score", value: "6" },
    {
      id: 649705,
      key: "wc_productdata_options",
      value: [
        {
          _product_block: "0",
          _top_content: "",
          _bottom_content: "",
          _bubble_new: "",
          _bubble_text: "",
          _custom_tab_title: "",
          _custom_tab: "",
          _product_video: "",
          _product_video_size: "",
          _product_video_placement: "",
        },
      ],
    },
    { id: 649706, key: "ced_ebay_plugin_profile_template", value: "" },
    { id: 649707, key: "ced_ebay_plugin_profile_condition", value: "" },
    {
      id: 649708,
      key: "ced_ebay_plugin_profile_condition_descriptor",
      value: "",
    },
    {
      id: 649709,
      key: "ced_ebay_plugin_profile_condition_descriptor_values",
      value: "",
    },
    { id: 649710, key: "qb_income_account", value: "" },
    { id: 649711, key: "qb_cogs_account", value: "" },
    { id: 649712, key: "qb_ia_account", value: "" },
    { id: 649713, key: "qb_p_category", value: "" },
    { id: 649714, key: "qb_p_cost", value: "0" },
  ],
  stock_status: "instock",
  has_options: false,
  post_password: "",
  global_unique_id: "",
  brands: [],
  _links: {
    self: [
      {
        href: "https://lanco-corp.com/wp-json/wc/v3/products/40679",
        targetHints: { allow: ["GET", "POST", "PUT", "PATCH", "DELETE"] },
      },
    ],
    collection: [{ href: "https://lanco-corp.com/wp-json/wc/v3/products" }],
  },
}
