import { InMemoryCache } from "@apollo/client"
// generated by Fragment Matcher plugin
import introspectionResult from "../api/gql/fragment-matcher"

import { concatPagination } from "@apollo/client/utilities"

export const cache: InMemoryCache = new InMemoryCache({
  possibleTypes: introspectionResult.possibleTypes,
  typePolicies: {
    Query: {
      fields: {
        allPosts: concatPagination(),
        getMenuItems: () => {
          return menuItemsVar()
        },
      },
    },
  },
})

export type NormalizedMenuItem = {
  path: string
  label: string
  id: string
  children: NormalizedMenuItem[] | null
  mega?: boolean
}

export const initialMenu: NormalizedMenuItem[] = [
  {
    id: "Home",
    path: "/",
    label: "Home",
    children: null,
  },
  {
    id: "Products",
    path: "/products",
    label: "Products",
    children: null,
  },
  {
    id: "RonaBev",
    path: "/products/ronabev",
    label: "Ronabev",
    children: null,
  },
  {
    id: "RonaTank",
    path: "/products/ronatank",
    label: "RonaTank",
    children: null,
  },
  {
    id: "Consulting",
    path: "/services/consulting",
    label: "Consulting",
    children: null,
  },
  {
    id: "Company",
    path: "/about",
    label: "Company",
    children: null,
  },
]

export const menuItemsVar = cache.makeVar(initialMenu)
