import { InMemoryCache } from "@apollo/client"
// generated by Fragment Matcher plugin
import introspectionResult from "../api/gql/fragment-matcher"

import { concatPagination } from "@apollo/client/utilities"

export const cache: InMemoryCache = new InMemoryCache({
  possibleTypes: introspectionResult.possibleTypes,
  typePolicies: {
    Query: {
      fields: {
        allPosts: concatPagination(),
        getMenuItems: () => {
          return menuItemsVar()
        },
      },
    },
  },
})

export type NormalizedMenuItem = {
  path: string
  label: string
  children: NormalizedMenuItem[] | null
}

export const initialMenu: NormalizedMenuItem[] = [
  {
    path: "/",
    label: "Home",
    children: null,
  },
]

export const menuItemsVar = cache.makeVar(initialMenu)
